version: "3"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
 square:
    image: paddub/square-docker
    ports:
      - 8080:9090
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    depends_on:
      - mysql_db
volumes:
  db:
