version: "3"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  cube:
    build:
      context: ./serviceCube
      dockerfile: Dockerfile
    ports:
      - 8080:9090
    environment:
      - SPRING_DATASOURCE_URL= jdbc:mysql://mysql_db:3306/docker_db?autoReconnect=docker_db&useSSL=false
    depends_on:
      - mysql_db
volumes:
  db:
