version: "3"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    networks:
      - mysql_spring
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  cube:
    build:
      context: ./serviceCube
      dockerfile: Dockerfile
    networks:
      - mysql_spring
    ports:
      - 8080:9090
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/docker_db?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    depends_on:
      - mysql_db
volumes:
  db:
networks:
  mysql_spring:
