version: "3"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    ports:
      - 3307:3306
    networks:
      - spring-mysql
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
  cube:
    depends_on:
      - mysql_db
    build:
      context: ./serviceCube
      dockerfile: Dockerfile
    ports:
      - 8080:9090
    networks:
      - spring-mysql
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
volumes:
  db:
networks:
  spring-mysql:
