version: "3"

services:
  mysql_db:
    container_name: mysql_db
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
  cube:
    depends_on:
      - mysql_db
    build:
      context: ./serviceCube
      dockerfile: Dockerfile
    ports:
      - 8080:9090
    command: sh -c './wait-for mysql_db:3306 -- npm start'
volumes:
  db:
