version: "3"

volumes:
  db:
networks:
  spring-mysql:
services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    restart: always
    ports:
      - 3307:3306
    networks:
      - spring-mysql
    environment:
      - MYSQL_DATABASE=docker_db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
