version: "3"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33067:33067
    volumes:
      - db:/var/lib/mysql
  fibonacci:
    build:
      context: ./serviceFibonacci
      dockerfile: Dockerfile
    ports:
      - 8080:9090
    environment:
      - DB_HOST=mysqldb
      - DB_NAME=docker_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - mysql_db
volumes:
  db:
